# Basic linear algebra in Julia
Author: Andreas Noack Jensen (MIT & JuliaComputing) (https://twitter.com/anoackjensen?lang=en)
(with edits from Jane Herriman)

First let's define a random matrix

In [21]:
A = rand(1:4,3,3)

3×3 Matrix{Int64}:
 2  3  3
 2  4  2
 4  2  2

Define a vector of ones

In [22]:
x = fill(1.0, (3,)) # = fill(1.0, 3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

Notice that $A$ has type Array{Int64,2} but $x$ has type Array{Float64,1}. Julia defines the aliases Vector{Type}=Array{Type,1} and Matrix{Type}=Array{Type,2}. 

Many of the basic operations are the same as in other languages
#### Multiplication

In [23]:
b = A*x

3-element Vector{Float64}:
 8.0
 8.0
 8.0

#### Transposition
As in other languages `A'` is the conjugate transpose, or adjoint

In [24]:
A'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 2  2  4
 3  4  2
 3  2  2

and we can get the transpose with

In [25]:
?transpose

search: transpose



```
transpose(A)
```

Lazy transpose. Mutating the returned object should appropriately mutate `A`. Often, but not always, yields `Transpose(A)`, where `Transpose` is a lazy transpose wrapper. Note that this operation is recursive.

This operation is intended for linear algebra usage - for general data manipulation see [`permutedims`](@ref Base.permutedims), which is non-recursive.

# Examples

```jldoctest
julia> A = [3+2im 9+2im; 8+7im  4+6im]
2×2 Matrix{Complex{Int64}}:
 3+2im  9+2im
 8+7im  4+6im

julia> transpose(A)
2×2 transpose(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 3+2im  8+7im
 9+2im  4+6im
```


In [26]:
transpose(A)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 2  2  4
 3  4  2
 3  2  2

#### Transposed multiplication
Julia allows us to write this without *

In [27]:
A'A

3×3 Matrix{Int64}:
 24  22  18
 22  29  21
 18  21  17

#### Solving linear systems 
The problem $Ax=b$ for ***square*** $A$ is solved by the \ function.

In [28]:
A\b

3-element Vector{Float64}:
 1.0
 1.0
 1.0

`A\b` gives us the *least squares solution* if we have an overdetermined linear system (a "tall" matrix)

In [29]:
Atall = rand(3, 2)

3×2 Matrix{Float64}:
 0.518301   0.284985
 0.855072   0.227019
 0.0102318  0.365172

In [30]:
Atall\b

2-element Vector{Float64}:
  3.5491061848783576
 21.762001096807644

and the *minimum norm least squares solution* if we have a rank-deficient least squares problem

In [31]:
v = rand(3)
rankdef = hcat(v, v)

3×2 Matrix{Float64}:
 0.0222053  0.0222053
 0.14772    0.14772
 0.563893   0.563893

In [32]:
rankdef\b

2-element Vector{Float64}:
 8.625802335202868
 8.625802335202872

Julia also gives us the minimum norm solution when we have an underdetermined solution (a "short" matrix)

In [33]:
bshort = rand(2)
Ashort = rand(2, 3)

2×3 Matrix{Float64}:
 0.331598  0.220304  0.437562
 0.961089  0.110671  0.920583

In [34]:
Ashort\bshort

3-element Vector{Float64}:
 -0.9561604180565435
  3.2339835416675187
  1.28647325621642

# The LinearAlgebra library

While much of linear algebra is available in Julia by default (as shown above), there's a standard library named `LinearAlgebra` that brings in many more relevant names and functions. In particular, it provides factorizations and some structured matrix types.  As with all packages, you can bring these additional features into your session with a `using LinearAlgebra`.

### Exercises

#### 10.1 
Take the inner product (or "dot" product) of a vector `v` with itself and assign it to variable `dot_v`.



In [35]:
v = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [36]:
using LinearAlgebra

In [40]:
dot_v = dot(v, v)

14

In [41]:
@assert dot_v == 14

In [43]:
dot_v = v ⋅ v
@assert dot_v == 14

#### 10.2 
Take the outer product of a vector v with itself and assign it to variable `outer_v`

In [45]:
v'

1×3 adjoint(::Vector{Int64}) with eltype Int64:
 1  2  3

In [47]:
outer_v = v * v'

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

In [48]:
@assert outer_v == [1 2 3
                    2 4 6
                    3 6 9]

In [50]:
cross_v = cross(v, v)

3-element Vector{Int64}:
 0
 0
 0

In [51]:
@assert cross_v == [0, 0, 0]