# Loops

Topics:
1. `while` loops
2. `for` loops
<br>

## while loops

The syntax for a `while` is

```julia
while *condition*
    *loop body*
end
```

For example, we could use `while` to count or to iterate over an array.

In [1]:
n = 0
while n < 10
    n += 1
    println(n)
end
n

1
2
3
4
5
6
7
8
9
10


10

In [2]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]

i = 1
while i <= length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you!")
    i += 1
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [3]:
for f in myfriends
    println(f)
end

Ted
Robyn
Barney
Lily
Marshall


## for loops

The syntax for a `for` loop is

```julia
for *var* in *loop iterable*
    *loop body*
end
```

We could use a for loop to generate the same results as either of the examples above:

In [4]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [5]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]

for friend in myfriends
    println("Hi $friend, it's great to see you!")
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


Now let's use `for` loops to create some addition tables, where the value of every entry is the sum of its row and column indices. <br>

Note that we iterate over this array via column-major loops in order to get the best performance. More information about fast indexing of multidimensional arrays inside nested loops can be found at https://docs.julialang.org/en/v1/manual/performance-tips/#Access-arrays-in-memory-order,-along-columns-1

First, we initialize an array with zeros.

In [15]:
m, n = 5, 5
A = fill(0, (m, n))

5×5 Matrix{Int64}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [7]:
?fill

search: fill fill! finally findall filter filter! filesize filemode isfile



```
fill(x, dims::Tuple)
fill(x, dims...)
```

Create an array filled with the value `x`. For example, `fill(1.0, (5,5))` returns a 5×5 array of floats, with each element initialized to `1.0`.

`dims` may be specified as either a tuple or a sequence of arguments. For example, the common idiom `fill(x)` creates a zero-dimensional array containing the single value `x`.

# Examples

```jldoctest
julia> fill(1.0, (2,3))
2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

julia> fill(42)
0-dimensional Array{Int64, 0}:
42
```

If `x` is an object reference, all elements will refer to the same object:

```jldoctest
julia> A = fill(zeros(2), 2);

julia> A[1][1] = 42; # modifies both A[1][1] and A[2][1]

julia> A
2-element Vector{Vector{Float64}}:
 [42.0, 0.0]
 [42.0, 0.0]
```


In [16]:
for j in 1:n
    for i in 1:m
        A[i, j] = i + j
    end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

Here's some syntactic sugar for the same nested `for` loop

In [17]:
B = fill(0, (m, n))

5×5 Matrix{Int64}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [18]:
for j in 1:n, i in 1:m
    B[i, j] = i + j
end
B

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

The more "Julia" way to create this addition table would have been with an *array comprehension*.

In [19]:
C = [i + j for i in 1:m, j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

### Exercises

#### 4.1 
Loop over integers between 1 and 100 and print their squares.

In [22]:
for i in 1:100
    square = i ^ 2
    println("$i -> $square")
end

1 -> 1
2 -> 4
3 -> 9
4 -> 16
5 -> 25
6 -> 36
7 -> 49
8 -> 64
9 -> 81
10 -> 100
11 -> 121
12 -> 144
13 -> 169
14 -> 196
15 -> 225
16 -> 256
17 -> 289
18 -> 324
19 -> 361
20 -> 400
21 -> 441
22 -> 484
23 -> 529
24 -> 576
25 -> 625
26 -> 676
27 -> 729
28 -> 784
29 -> 841
30 -> 900
31 -> 961
32 -> 1024
33 -> 1089
34 -> 1156
35 -> 1225
36 -> 1296
37 -> 1369
38 -> 1444
39 -> 1521
40 -> 1600
41 -> 1681
42 -> 1764
43 -> 1849
44 -> 1936
45 -> 2025
46 -> 2116
47 -> 2209
48 -> 2304
49 -> 2401
50 -> 2500
51 -> 2601
52 -> 2704
53 -> 2809
54 -> 2916
55 -> 3025
56 -> 3136
57 -> 3249
58 -> 3364
59 -> 3481
60 -> 3600
61 -> 3721
62 -> 3844
63 -> 3969
64 -> 4096
65 -> 4225
66 -> 4356
67 -> 4489
68 -> 4624
69 -> 4761
70 -> 4900
71 -> 5041
72 -> 5184
73 -> 5329
74 -> 5476
75 -> 5625
76 -> 5776
77 -> 5929
78 -> 6084
79 -> 6241
80 -> 6400
81 -> 6561
82 -> 6724
83 -> 6889
84 -> 7056
85 -> 7225
86 -> 7396
87 -> 7569
88 -> 7744
89 -> 7921
90 -> 8100
91 -> 8281
92 -> 8464
93 -> 8649
94 -> 8836
95 -> 9025
96 -> 9

#### 4.2 
Add to the code above a bit to create a dictionary, `squares` that holds integers and their squares as key, value pairs such that

```julia
squares[10] == 100
```

In [23]:
squares = Dict{Int64, Int64}()

Dict{Int64, Int64}()

In [26]:
for i in 1:100
    squares[i] = i ^ 2
end

In [27]:
@assert squares[10] == 100
@assert squares[11] == 121

#### 4.3 
Use an array comprehension to create an an array `squares_arr` that stores the squares for all integers between 1 and 100.

In [28]:
squares_arr = [i ^ 2 for i in 1:100]

100-element Vector{Int64}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

In [29]:
@assert length(squares_arr) == 100
@assert sum(squares_arr) == 338350